### ISSUE TITLE
Feature: Add Docker ENV for start of channel numbering

### ISSUE THREAD

**Issue by dschaper** [matthuisman/frndlytv-for-channels#1]
Can you add the `channel-number` tag to the EXT lines that begins numbering with a user supplied env var? 

This would allow the channels to be placed strategically, I imagine making `channel-number` a counter that starts at the user supplied value and increments by one every time through the loop.

Thanks!

**Comment by matthuisman** [comment]
good idea - I was thinking of something similar just yesterday after reading this:
https://community.getchannels.com/t/adding-plutotv-and-changing-channel-numbers/24796

**Comment by matthuisman** [comment]
ok done: https://github.com/matthuisman/frndlytv-for-channels/commit/e5b6c58e59c2d1a02197f835a207340ac7dd9725

Pull the latest docker image, and then add **?start_chno=50** to the end of the playlist url in Channels
eg. http://127.0.0.1:8183/playlist.m3u?start_chno=50

Change 50 to what you want to be the starting channel number
