### ISSUE TITLE
secure webserver

### ISSUE THREAD

**Issue by t3chguru36** [matthuisman/frndlytv-for-channels#12]
I like this script but is there anyway to run the python script with a hosted https server instead of http

**Comment by matthuisman** [comment]
sorry, no plans to implement this.
You could put the app behing a nginx reverse proxy with SSL if you like.
Or try to edit the python webserver to do https

**Comment by t3chguru36** [comment]
Ok I tried to edit the webserver to do https but im clueless lol

Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, May 31, 2024 at 3:55 AM, Matt ***@***.***> wrote:   


sorry, no plans to implement this.
You could put the app behing a nginx reverse proxy with SSL if you like.
Or try to edit the python webserver to do https

**Comment by matthuisman** [comment]
https in python can be tricky.
Its always recommended do do a nginx reverse proxy infront of it that handles the cert

Id also ask yourself why you even want https.
the username / password is passed in as env or cmdline variables (not sent over http)
All comms to frndly servers is via https.

More hassle than its worth id suggest

**Comment by t3chguru36** [comment]
I need secure authentication to the builtin webserver because hackers are trying to pass commands to the script and changing the port number that the webserver is bound to does nothing they find it I also have a domain name so hackers can find the external ip address easily by using nslookup and when they send stupid commands to this script it crashes it and I have to restart it

Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, May 31, 2024 at 5:38 PM, Matt ***@***.***> wrote:   


https in python can be tricky.
Its always recommended do do a nginx reverse proxy infront of it that handles the cert

Id also ask yourself why you even want https.
the username / password is passed in as env or cmdline variables (not sent over http)
All comms to frndly servers is via https.

More hassle than its worth id suggest

**Comment by matthuisman** [comment]
run it locally. dont expose to web.....

**Comment by matthuisman** [comment]
also https wont help with that. they can still find it and send stupid commands to it

**Comment by matthuisman** [comment]
https only helps stop MITM (someone seeing the traffic from your browser to the server)
If there is nothing sensitive in that data - like for this container - there is no point.

**Comment by t3chguru36** [comment]
Well im trying to setup a seperate https authentication webserver so without proper authentication they cant access the script 

Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, May 31, 2024 at 6:08 PM, Matt ***@***.***> wrote:   


also https wont help with that. they can still find it and send stupid commands to it

**Comment by matthuisman** [comment]
sounds like your trying to re-sell frndly tv services and make a buck.
i dont want any part for that.
I can tell you'll fail anyway as you dont seem very knowledgable

**Comment by t3chguru36** [comment]
Well I have another server that has to be exposed to the internet so that doesnt help 

Yahoo Mail: Search, Organize, Conquer 
 
  On Fri, May 31, 2024 at 6:07 PM, Matt ***@***.***> wrote:   


run it locally. dont expose to web.....
