### ISSUE TITLE
ModuleNotFoundError: No module named 'requests' on Linux terminal

### ISSUE THREAD

**Issue by 27hectormanuel** [matthuisman/frndlytv-for-channels#13]
![friendlytv](https://github.com/matthuisman/frndlytv-for-channels/assets/22853711/6927c695-afd9-41ce-831c-4a9835b625ae)
![friendlytv2](https://github.com/matthuisman/frndlytv-for-channels/assets/22853711/ebe4ed1d-c180-4898-8845-633fe99117ad)

**Comment by matthuisman** [comment]
Install the python requirements.txt

**Comment by 27hectormanuel** [comment]
I have been trying - 
![image](https://github.com/matthuisman/frndlytv-for-channels/assets/22853711/ab1acabc-0c45-414b-874b-3ccfdfe504f9)

**Comment by matthuisman** [comment]
You don't have pip installed. Google how to install that on your Linux distro.

**Comment by 27hectormanuel** [comment]
> You don't have pip installed. Google how to install that on your Linux distro.

![image](https://github.com/matthuisman/frndlytv-for-channels/assets/22853711/afea287f-84c5-4fad-bd67-9db3c3e42421)
I alredy had everything installed. could be the steam os update  that messes with sudo apps
