### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by RJ-Make** [matthuisman/frndlytv-for-channels#2]
May be related to new channels that were added 

Error: Extra data: line 1 column 4 (char 3)

I'm on the latest version.

**Comment by matthuisman** [comment]
when are you getting that error?

Please make sure your running latest container version

**Comment by RJ-Make** [comment]
Thanks for the quick reply. 

I noticed you did some work recently adding the channel number option so I pulled the very latest and it all seems to be working now.
