### ISSUE TITLE
Stopped playing channels

### ISSUE THREAD

**Issue by Gthubln060920** [matthuisman/frndlytv-for-channels#3]
I deleted Channels source, deleted container, downloaded latest, added container and source, download guide.
Guide populates correctly.
Running on Synology 918+ DSM 6.2.4-25556 Update 2

logging in....	stdout
13:26:26	logged in!	stdout
13:27:59	172.17.0.1 - - [19/Nov/2021 13:27:59] "GET /playlist.m3u?start_chno=70 HTTP/1.1" 200 -	stdout
13:27:59	No gracenote id found in epg map for: 37	stdout
13:27:59	No gracenote id found in epg map for: 16	stdout
13:27:59	No gracenote id found in epg map for: 38	stdout
13:28:00	172.17.0.1 - - [19/Nov/2021 13:28:00] "GET /playlist.m3u?start_chno=70 HTTP/1.1" 200 -	stdout
13:28:00	No gracenote id found in epg map for: 37	stdout
13:28:00	No gracenote id found in epg map for: 16	stdout
13:28:00	No gracenote id found in epg map for: 38	stdout
13:29:40	172.17.0.1 - - [19/Nov/2021 13:29:40] "GET /play/21 HTTP/1.1" 500 -	stdout
13:29:40	----------------------------------------	stdout
13:29:40	Exception happened during processing of request from ('172.17.0.1', 59192)	stdout
13:29:40	Traceback (most recent call last):	stdout
13:29:40	File "/usr/local/lib/python3.8/socketserver.py", line 683, in process_request_thread	stdout
13:29:40	self.finish_request(request, client_address)	stdout
13:29:40	File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request	stdout
13:29:40	self.RequestHandlerClass(request, client_address, self)	stdout
13:29:40	File "./app.py", line 74, in __init__	stdout
13:29:40	super().__init__(*args, **kwargs)	stdout
13:29:40	File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__	stdout
13:29:40	self.handle()	stdout
13:29:40	File "/usr/local/lib/python3.8/http/server.py", line 427, in handle	stdout
13:29:40	self.handle_one_request()	stdout
13:29:40	File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request	stdout
13:29:40	method()	stdout
13:29:40	File "./app.py", line 101, in do_GET	stdout
13:29:40	self._error(e)	stdout
13:29:40	File "./app.py", line 99, in do_GET	stdout
13:29:40	routes[func]()	stdout
13:29:40	File "./app.py", line 131, in _play	stdout
13:29:40	raise Exception(f'Unable to find live stream for: {id}')	stdout
13:29:40	Exception: Unable to find live stream for: 21	stdout
13:29:40	----------------------------------------	stdout
13:29:42	172.17.0.1 - - [19/Nov/2021 13:29:42] "GET /play/21 HTTP/1.1" 500 -	stdout
13:29:42	----------------------------------------	stdout
13:29:42	Exception happened during processing of request from ('172.17.0.1', 59198)	stdout
13:29:42	Traceback (most recent call last):	stdout
13:29:42	File "/usr/local/lib/python3.8/socketserver.py", line 683, in process_request_thread	stdout
13:29:42	self.finish_request(request, client_address)	stdout
13:29:42	File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request	stdout
13:29:42	self.RequestHandlerClass(request, client_address, self)	stdout
13:29:42	File "./app.py", line 74, in __init__	stdout
13:29:42	super().__init__(*args, **kwargs)	stdout
13:29:42	File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__	stdout
13:29:42	self.handle()	stdout
13:29:42	File "/usr/local/lib/python3.8/http/server.py", line 427, in handle	stdout
13:29:42	self.handle_one_request()	stdout
13:29:42	File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request	stdout
13:29:42	method()	stdout
13:29:42	File "./app.py", line 101, in do_GET	stdout
13:29:42	self._error(e)	stdout
13:29:42	File "./app.py", line 99, in do_GET	stdout
13:29:42	routes[func]()	stdout
13:29:42	File "./app.py", line 131, in _play	stdout
13:29:42	raise Exception(f'Unable to find live stream for: {id}')	stdout
13:29:42	Exception: Unable to find live stream for: 21	stdout
13:29:42	----------------------------------------	stdout
13:29:43	172.17.0.1 - - [19/Nov/2021 13:29:43] "GET /play/21 HTTP/1.1" 500 -	stdout
13:29:43	----------------------------------------	stdout
13:29:43	Exception happened during processing of request from ('172.17.0.1', 59204

**Comment by matthuisman** [comment]
please try latest container. should be fixed
