### ISSUE TITLE
Not Playing Again. 

### ISSUE THREAD

**Issue by RJ-Make** [matthuisman/frndlytv-for-channels#4]
I just pulled the latest, after not being able to tune a channel. Docker Logs Below. 

I have confirmed password is correct and the Frndly TV service is up. 

> 172.17.0.1 - - [26/Nov/2021 15:07:49] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:50] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:51] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:51] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:52] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:52] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> Starting server on port 80
> 
> logging in....
> 
> Logged in!
> 
> No gracenote id found in epg map for: 37
> 
> No gracenote id found in epg map for: 16
> 
> No gracenote id found in epg map for: 38
> 
> No gracenote id found in epg map for: 37
> 
> No gracenote id found in epg map for: 16
> 
> No gracenote id found in epg map for: 38
> 
> Starting server on port 80
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:53] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:53] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:54] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:54] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:55] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:56] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:56] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:56] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:56] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:57] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:07:58] "GET /play2/gracenote HTTP/1.1" 404 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:08:24] "GET /playlist.m3u HTTP/1.1" 200 -
> 
> 172.17.0.1 - - [26/Nov/2021 15:10:55] "GET /playlist.m3u HTTP/1.1" 200 -

**Comment by matthuisman** [comment]
Your still using old play paths. You need to fetch the playlist again to
get the correct paths

**Comment by matthuisman** [comment]
Actually, I think your not using latest container. Try update container

**Comment by RJ-Make** [comment]
Strange, very strange. This is what I did before posting yesterday. 

1) Pulled the latest container. (first stopped, removed, pulled, and restarted)
2) Deleted and Recreated Database and Re-downloaded entire guide. 

Was still was not working.

Followed the same exact process just now and now it works. 

I just don't get what I may be doing wrong with these updated containers. :-)
