### ISSUE TITLE
DRM with certain channels

### ISSUE THREAD

**Issue by ghost** [matthuisman/frndlytv-for-channels#6]
A&E and History seem to be using DRM and they fail to play now. Just letting you know in case you don't.

**Comment by matthuisman** [comment]
yes, they did that in December sometime:
https://community.getchannels.com/t/frndly-tv-for-channels/29078/138?u=matthuisman
(there note there how you can exclude them)

unfortunately there is no easy / quick way the playlist generator knows which are DRM'd and skip them
