### ISSUE TITLE
EPG Update (Request)

### ISSUE THREAD

**Issue by joerich** [matthuisman/frndlytv-for-channels#8]
Any chance you could update the EPG to include the new channels added??

**Comment by matthuisman** [comment]
As per the thread on Channels, people just need to let me know the name and
gracenote Id of each new channel

**Comment by matthuisman** [comment]
epg for Decades, Heroes & Icons, Start TV will be live in 60mins

**Comment by joerich** [comment]
You are totally awesome! Thank you!
Love your container! works great!
